apiVersion: v1
kind: Service
metadata:
  namespace: programmer
  name: alb-programmer
  labels:
    service: lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    service: programmer
