apiVersion: v1
kind: Service
metadata:
  name: tester-service
  labels:
    service: tester
  namespace: tester
spec:
  ports:
    - port: 80
      name: tester-service-port
  selector:
    service: tester
