apiVersion: v1
kind: Service
metadata:
  namespace: tester
  name: alb-tester
  labels:
    service: lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    service: tester
